import type { ComebackDashboardData } from "@/lib/types";

export const demoDashboardData: ComebackDashboardData = {
  athleteName: "Peter",
  eventFocus: "Sprint triathlon rebuild",
  eventDate: "2026-09-20",
  weekNumber: 7,
  plannedWorkouts: [
    {
      id: "tp-1",
      date: "2026-06-14",
      title: "Aerobic run + strides",
      source: "coros",
      sport: "Run",
      duration: "50 min",
      intensity: "Z2 with 6 x 20 sec",
    },
    {
      id: "tp-2",
      date: "2026-06-15",
      title: "Lower strength",
      source: "manual",
      sport: "Gym",
      duration: "60 min",
      intensity: "RPE 7",
    },
    {
      id: "tp-3",
      date: "2026-06-16",
      title: "CSS technique swim",
      source: "coros",
      sport: "Swim",
      duration: "45 min",
      intensity: "Drills + threshold touch",
    },
  ],
  activitySummary: {
    sessions: 8,
    hours: 6.7,
    distanceKm: 48.4,
    elevationM: 612,
    source: "coros",
  },
  metrics: [
    {
      id: "bodyweight",
      label: "Bodyweight",
      kind: "bodyweight",
      value: "91.8 kg",
      delta: "-3.4 kg",
      trend: "down",
      since: "1 May 2026",
    },
    {
      id: "squat",
      label: "Back squat",
      kind: "lift",
      value: "125 kg",
      delta: "+10 kg",
      trend: "up",
      since: "1 May 2026",
    },
    {
      id: "run-threshold",
      label: "Run threshold",
      kind: "running_threshold",
      value: "4:48 /km",
      delta: "12 sec faster",
      trend: "up",
      since: "1 May 2026",
    },
    {
      id: "ftp",
      label: "Bike FTP",
      kind: "ftp",
      value: "258 W",
      delta: "+14 W",
      trend: "up",
      since: "1 May 2026",
    },
    {
      id: "css",
      label: "Swim CSS",
      kind: "css",
      value: "1:48 /100m",
      delta: "3 sec faster",
      trend: "up",
      since: "1 May 2026",
    },
    {
      id: "custom-sprint-tri",
      label: "Sprint tri marker",
      kind: "custom",
      value: "Bike-run brick",
      delta: "2 weeks consistent",
      trend: "flat",
      since: "1 June 2026",
    },
  ],
  wellness: {
    date: "2026-06-13",
    waterLitres: 2.4,
    waterTargetLitres: 3,
    caloriesHit: true,
    readiness: 76,
    sleepHours: 7.1,
    sleepSource: "coros",
    hrvMs: 58,
    restingHeartRate: 49,
    painFlag: "No red flags",
  },
  photos: [],
  nextActions: [
    "Connect COROS for activity, sleep, HRV, resting HR, and daily summaries.",
    "Keep Strava as an optional activity mirror and public/social proof source.",
    "Use COROS/TrainingPeaks planned workout import if API access allows it; otherwise use manual or CSV.",
    "Set baseline dates for bodyweight, lifts, threshold pace, FTP, CSS, and the custom event marker.",
  ],
};
